### ISSUE TITLE
Sync ESLint and TSConfig with Penumbra Web

### ISSUE THREAD

**Issue by VanishMax** [prax-wallet/prax#103]
Penumbra Web introduced great changes to the global tsconfig and eslint: [here](https://github.com/penumbra-zone/web/pull/1460) and [here](https://github.com/penumbra-zone/web/pull/1461). Would be nice for Prax to follow the same structure

====

Should come after: https://github.com/penumbra-zone/web/issues/1762

**Comment by grod220** [comment]
Should wait until https://github.com/penumbra-zone/web/issues/1668 is completed

**Comment by TalDerei** [comment]
what's the status of the eslint work https://github.com/prax-wallet/prax/pull/194?

**Comment by vacekj** [comment]
working on it next

**Comment by TalDerei** [comment]
closed as resolved
