### ISSUE TITLE
Select & enable numeraires

### ISSUE THREAD

**Issue by grod220** [prax-wallet/prax#196]
A decent amount of work ([tracking issue](https://github.com/penumbra-zone/web/issues/530)) has been done to enable prax to keep an index of prices. Since the launch of mainnet, this feature has not been enabled because [numeraires in the registry](https://github.com/prax-wallet/registry/blob/main/registry/chains/penumbra-1.json#L1517) have not been chosen.

Tasks:
- Select appropriate numeraires
- Add them to the registry
- Test out onboarding (especially [this logic](https://github.com/prax-wallet/prax/blob/29aed271edc299b6ecb66a57e89f6b67c9046138/apps/extension/src/shared/components/numeraires-form.tsx#L31-L39))
- Test out Prax settings page
- See equivalent prices displayed in minifront
- Communicate to users the new feature

**Comment by TalDerei** [comment]
closed by https://github.com/prax-wallet/prax/pull/203?

**Comment by grod220** [comment]
Indeed!
